spring.application.name=LadenZeitServer

## Netowrk
server.address=0.0.0.0
server.port=8080

## Logging
logging.level.root=WARN
logging.level.com.nakamura_labs=DEBUG

## MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ladenzeit?serverTimezone=UTC
spring.datasource.username=ladenzeit
spring.datasource.password=ladenzeit

## Google Maps
com.google.maps.api.key=${MAPS_API_KEY:}

## Own
com.nakamura_labs.ladenzeit.place_cache_hours = 6
com.nakamura_labs.ladenzeit.cookie_expire_hours = 6
com.nakamura_labs.ladenzeit.otp_expire_minutes = 15
